---
- hosts: localhost
  user: root

  vars_files:
    - vars.yml

  pre_tasks:
    - include_vars: secrets.yml
      ignore_errors: yes
      tags:
        - always

  roles:
    - facts
    - nodejs

  post_tasks:
    - name: Add Sauce Labs secrets
      blockinfile:
        dest: /home/vagrant/.bashrc
        block: |
          export {{ item }}
        marker: "# {mark} ANSIBLE MANAGED BLOCK {{item}}"
      with_items: "{{ secrets_env_vars }}"
      tags:
        - always

    - name: Increase open files limit for Sauce Labs 
      template:
        src: vagrant-open-files-limit.conf      
        dest: /etc/security/limits.d/90-vagrant.conf
        owner: root
        group: root
        mode: 0644
      tags:
        - always
